---
- hosts: all
  become: yes
  tasks:
    - name: Create new users
      user:
        name: '{{ item.name }}'
        uid: '{{ item.uid }}'
        state: present

      loop:
        - name: talha
          uid: 1027
        - name: ibrah
          uid: 1007
        - name: shadman
          uid: 1017
